import streamlit as st
import json

st.set_page_config(page_title="F1 AI Race Predictor", page_icon="🏎️", layout="centered")

st.title("🏎️ Formula 1 Race Position Predictor")
st.write("This machine learning model predicts a driver's final race standing based on historical patterns.")

st.markdown("---")

# Load the predictions file generated by our engine
try:
    with open("predictions.json", "r") as f:
        predictions_data = json.load(f)
        
    st.subheader("🤖 Upcoming Race Simulation Results")
    st.write("Based on current grid positions, here is where our AI expects drivers to finish:")
    
    # Display the results cleanly
    for item in predictions_data:
        st.write(f"**Starts P{item['grid']}** ➡️ Predicted Finish: **P{item['predicted_finish']}**")

except FileNotFoundError:
    st.error("No predictions found yet! Run the predictor pipeline script first.")
